#!/usr/bin/env python3
"""Generates crates/izul-redact/src/std14_data.rs from reportlab's copy of the
Adobe Core 14 AFM metrics and the standard PDF encodings.

Why generated: a redaction that takes a glyph out of a line must put exactly
its advance back, or every glyph after it on the line moves. Fonts written
without /Widths (allowed for the standard 14) are measured from these tables,
and a table typed from memory is exactly the kind of guess this project does
not ship. reportlab (BSD licence) carries the AFM widths by glyph name and the
encodings as glyph-name vectors; this script only reformats them.

Run:  python3 tools/std14/build.py
"""
from pathlib import Path

from reportlab.pdfbase import _fontdata as fd

OUT = Path(__file__).resolve().parents[2] / "crates/izul-redact/src/std14_data.rs"

ENCODINGS = [
    ("STANDARD", "StandardEncoding"),
    ("WIN_ANSI", "WinAnsiEncoding"),
    ("MAC_ROMAN", "MacRomanEncoding"),
    ("SYMBOL", "SymbolEncoding"),
    ("ZAPF_DINGBATS", "ZapfDingbatsEncoding"),
]


def main() -> None:
    lines = [
        "// @generated by tools/std14/build.py from reportlab's Core 14 AFM data.",
        "// Do not edit by hand; run the script again.",
        "",
    ]
    for const, name in ENCODINGS:
        enc = fd.encodings[name]
        assert len(enc) == 256, name
        items = ", ".join('""' if g is None else f'"{g}"' for g in enc)
        lines.append(f"pub static {const}: [&str; 256] = [{items}];")
        lines.append("")
    lines.append("/// (base font, ascent, descent, widths sorted by glyph name)")
    lines.append("pub static FONTS: [(&str, i16, i16, &[(&str, u16)]); 14] = [")
    for font in fd.standardFonts:
        widths = fd.widthsByFontGlyph[font]
        asc, desc = fd.ascent_descent[font]
        if asc == 0 and desc == 0:
            # Symbol and ZapfDingbats carry no ascender in the AFM data
            # reportlab ships; the Helvetica values stand in (they only size
            # the box a glyph is judged by, never an advance).
            asc, desc = fd.ascent_descent["Helvetica"]
        pairs = ", ".join(f'("{g}", {w})' for g, w in sorted(widths.items()))
        lines.append(f'    ("{font}", {asc}, {desc}, &[{pairs}]),')
    lines.append("];")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
