#!/usr/bin/env node
/**
 * Regenerates `src/design/icons.generated.ts` from Fluent UI System Icons.
 *
 *   npm run icons
 *
 * Source: `@fluentui/svg-icons`, pinned below, MIT-licensed by Microsoft
 * (https://github.com/microsoft/fluentui-system-icons). The package is 87 MB
 * of SVG, so it is not a dependency: this script fetches the pinned tarball
 * once into a temporary folder, copies out the path data of the icons the
 * application actually uses, and writes them with the licence text into one
 * TypeScript module that *is* committed. Running the application or its build
 * never touches the network.
 *
 * Both the `regular` (outline) and the `filled` variant are taken for every
 * icon. They share their geometry, which is what lets `Icon.tsx` draw each one
 * as a two-tone glyph — a tinted fill under a coloured outline — from a single
 * consistent set rather than mixing sets (SPEC 12).
 */

import { execFileSync } from "node:child_process";
import { existsSync, mkdtempSync, readFileSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const VERSION = "1.1.341";
const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..");

/** Our name → Fluent's base name. Add a line here, then run `npm run icons`. */
const ICONS = {
  open: "folder_open",
  save: "save",
  saveAs: "save_edit",
  undo: "arrow_undo",
  redo: "arrow_redo",
  select: "cursor",
  hand: "hand_left",
  highlight: "highlight",
  underline: "text_underline",
  strike: "text_strikethrough",
  note: "note",
  comment: "comment",
  comments: "comment_multiple",
  textAdd: "text_add",
  textbox: "textbox",
  imageAdd: "image_add",
  ink: "inking_tool",
  pen: "pen",
  shapes: "shapes",
  line: "line",
  arrow: "arrow_up_right",
  rect: "rectangle_landscape",
  ellipse: "oval",
  polygon: "pentagon",
  stamp: "checkmark_starburst",
  delete: "delete",
  search: "search",
  zoomIn: "zoom_in",
  zoomOut: "zoom_out",
  rotateRight: "arrow_rotate_clockwise",
  rotateLeft: "arrow_rotate_counterclockwise",
  rotatePage: "rotate_right",
  thumbnails: "document_one_page_multiple",
  outline: "text_bullet_list_tree",
  bookmark: "bookmark_multiple",
  viewSingle: "document_one_page",
  viewDual: "book_open",
  viewCover: "document_one_page_columns",
  viewHorizontal: "document_landscape",
  fitWidth: "arrow_autofit_width",
  fitPage: "page_fit",
  actualSize: "ratio_one_to_one",
  first: "arrow_previous",
  previous: "chevron_left",
  next: "chevron_right",
  last: "arrow_next",
  sidebar: "panel_left",
  home: "home",
  add: "add",
  dismiss: "dismiss",
  minimize: "subtract",
  maximize: "maximize",
  restore: "square_multiple",
  star: "star",
  desktop: "desktop",
  pc: "laptop",
  folder: "folder",
  documents: "document_text",
  download: "arrow_download",
  drive: "hard_drive",
  recent: "clock",
  frequent: "history",
  info: "info",
  refresh: "arrow_clockwise",
  pdf: "document_pdf",
  chevronDown: "chevron_down",
  more: "more_horizontal",
  menu: "navigation",
  edit: "document_edit",
  // Phase 4: saving, exporting, and what happens around them.
  exportFile: "arrow_export_ltr",
  toImages: "image_multiple",
  flatten: "layer",
  extractPages: "document_arrow_right",
  warning: "warning",
  reload: "arrow_sync",
  draft: "document_sync",
  checkmark: "checkmark",
  error: "error_circle",
};
const SIZES = [20, 24];

const work = mkdtempSync(join(tmpdir(), "izul-icons-"));
try {
  execFileSync("npm", ["pack", `@fluentui/svg-icons@${VERSION}`, "--silent"], {
    cwd: work,
    stdio: ["ignore", "pipe", "inherit"],
    shell: process.platform === "win32",
  });
  execFileSync("tar", ["xzf", `fluentui-svg-icons-${VERSION}.tgz`], { cwd: work });
  const pkg = JSON.parse(readFileSync(join(work, "package/package.json"), "utf8"));
  if (pkg.license !== "MIT") throw new Error(`lisensi berubah: ${pkg.license}`);

  const dir = join(work, "package/icons");
  const paths = (file) => {
    const svg = readFileSync(join(dir, file), "utf8");
    if (/<(circle|rect|ellipse|polygon|g )/.test(svg)) throw new Error(`${file}: bukan path murni`);
    return [...svg.matchAll(/ d="([^"]+)"/g)].map((m) => m[1]);
  };

  const out = {};
  for (const [name, fluent] of Object.entries(ICONS)) {
    out[name] = {};
    for (const size of SIZES) {
      // A few icons are drawn at 20 px only; the 20 px geometry is then used
      // for both, and `v` tells `Icon.tsx` which viewBox it was drawn in.
      const v = existsSync(join(dir, `${fluent}_${size}_regular.svg`)) ? size : 20;
      out[name][size] = {
        v,
        r: paths(`${fluent}_${v}_regular.svg`),
        f: paths(`${fluent}_${v}_filled.svg`),
      };
    }
  }

  const header = `/**
 * GENERATED by tools/icons/build.mjs from @fluentui/svg-icons@${VERSION}.
 * Do not edit by hand; add the icon to the table in that script and rerun
 * \`npm run icons\`.
 *
 * Fluent UI System Icons — https://github.com/microsoft/fluentui-system-icons
 *
 * MIT License
 *
 * Copyright (c) 2020 Microsoft Corporation
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

export interface IconPaths {
  /** The viewBox edge the paths were drawn in. */
  readonly v: number;
  /** Outline variant. */
  readonly r: readonly string[];
  /** Filled variant, same geometry. */
  readonly f: readonly string[];
}

`;
  const body = `export const ICONS = ${JSON.stringify(out, null, 0)} as const satisfies Record<string, Record<20 | 24, IconPaths>>;

export type IconName = keyof typeof ICONS;
`;
  writeFileSync(join(ROOT, "src/design/icons.generated.ts"), header + body);
  console.log(`${Object.keys(ICONS).length} ikon ditulis ke src/design/icons.generated.ts`);
} finally {
  rmSync(work, { recursive: true, force: true });
}
